# Generated by Django 3.0.4 on 2020-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20200329_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("inprogress", "In progress"), ("completed", "Completed")],
                max_length=16,
                null=True,
            ),
        ),
    ]
