# Generated by Django 3.0.4 on 2020-04-01 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20200329_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresponse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task", name="details", field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="taskresponse",
            name="comment",
            field=models.TextField(max_length=2000),
        ),
    ]
