# Generated by Django 3.0.4 on 2020-04-01 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20200401_1637"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital", options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="task", options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="taskresponse", options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="hospital",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
