# Generated by Django 3.0.4 on 2020-04-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200401_1644"),
    ]

    operations = [
        migrations.RenameModel(old_name="Task", new_name="AidRequest",),
        migrations.RenameField(
            model_name="taskresponse", old_name="task", new_name="aid_request",
        ),
    ]
