# Generated by Django 3.0.4 on 2020-04-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20200401_2015"),
    ]

    operations = [
        migrations.RenameModel(old_name="TaskResponse", new_name="AidResponse",),
    ]
