# Generated by Django 3.0.4 on 2020-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20200401_2020"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital", old_name="location", new_name="city",
        ),
        migrations.AddField(
            model_name="hospital",
            name="address",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="phone",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="postal_code",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="state",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
