# Generated by Django 3.0.4 on 2020-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20200401_2121"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="personal_phone",),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="", max_length=16, verbose_name="personal phone"
            ),
            preserve_default=False,
        ),
    ]
