# Generated by Django 3.0.4 on 2020-04-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20200401_2138"),
    ]

    operations = [
        migrations.RemoveField(model_name="hospital", name="coordinates",),
        migrations.AddField(
            model_name="aidrequest",
            name="equipment_quantity",
            field=models.CharField(
                blank=True, help_text="only for new equipment request", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="aidrequest",
            name="equipment_type",
            field=models.CharField(
                blank=True, help_text="only for new equipment request", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="aidrequest",
            name="supply_quantity",
            field=models.CharField(
                blank=True, help_text="only for new supply quantity", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="aidrequest",
            name="supply_type",
            field=models.CharField(
                blank=True, help_text="only for new supply request", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="hospital", name="latitude", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="hospital", name="longitude", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="aidrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("equipment_repair", "Existing equipment repair"),
                    ("equipment_request", "New equipment request"),
                    ("supply_request", "New supply request"),
                    ("other_request", "Other request"),
                ],
                max_length=32,
            ),
        ),
    ]
