# Generated by Django 3.0.5 on 2020-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_auto_20200507_0855"),
    ]

    operations = [
        migrations.RemoveField(model_name="aidrequest", name="closed",),
        migrations.AddField(
            model_name="aidrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("in_progress", "In progress"),
                    ("closed", "Closed"),
                ],
                default="unassigned",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
