# Generated by Django 3.0.6 on 2020-06-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200521_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='comments',
            field=models.CharField(blank=True, max_length=200, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hospital', verbose_name='hospital'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=16, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='model',
            field=models.CharField(blank=True, max_length=16, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='type',
            field=models.CharField(choices=[('supply', 'New equipment/supply request'), ('repair', 'Existing equipment repair')], max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
