# Generated by Django 3.0.7 on 2020-06-05 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_auto_20200602_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
